### ISSUE TITLE
cant compile aarch64 ubuntu 20.04

### ISSUE THREAD

**Issue by bm16ton** [DebianDog/Gtkwialog#1]
i receive the following error
system_bash.c: In function ‘system_bash’:
system_bash.c:49:13: error: storage size of ‘pstat’ isn’t known
  union wait pstat;
             ^~~~~

**Comment by mcewanw** [comment]
BSD wait compatibility fix (union wait deprecated in glibc 2.25)

**Comment by mcewanw** [comment]
Fixed the glibc 2.25+ union wait deprecated so now compiles in BionicDog64;glibc 2.27, but still fails in latest Arch (glibc 2.31):
```
/usr/bin/ld: widget_window.o:/mnt/sda1/gtkwialog_github/Gtkwialog/src/gtkdialog.h:43: multiple definition of `function_signals_block'; gtkdialog.o:/mnt/sda1/gtkwialog_github/Gtkwialog/src/gtkdialog.h:43: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:486: gtkdialog] Error 1
make[1]: Leaving directory '/mnt/sda1/gtkwialog_github/Gtkwialog/src'
make: *** [Makefile:405: all] Error 2
```

Not sure what the issue is. Something seems to be getting defined more than once - older glibc didn't care.
NOTE: Same error with https://github.com/01micko/gtkdialog
Seems that gtkdialog.h needs variables split out before compiling when glibc 2.31
Workaround: compile on older system for now.

**Comment by bm16ton** [comment]
I've walking on needles for the past few years, knowing gtkdialog is
abandoned and probly not going to compile someday...your my hero for
continuing this work..I'm not a programmer can barely write a script and I
made a nice terminal emulator with drag and drop scp (to whatever folder
I'm currently she'd into) it feels good for a redneck fool like myself to
be able to do that. I have a fork of gtkdialog 8.4 the only thing I was
able to add to it was update the "if defined" for the arm,stuff In reverse
fix so that it works on aarch64. Again thank you for your response and for
continuing this great software! Your the man!

**Comment by mcewanw** [comment]
Thank you. I should mention that Arch Linux seems to use bash as its underlying system shell by default. In that case, as long as it is maintained, there is no disadvantage using gtkdialog rather than this gtkwialog fork, though no advantage either. Where gtkwialog is particularly useful is on the likes of Debian where dash is often (and by default) the underlying shell; in that case many apps written for gtkdialog simply won't work probably unless gtkwialog is used instead of traditional gtkdialog (the scrpts that won't work with traditional gtkdialog in that case are those that use bash functions, whether the shell script header asks for bash or not). Gtkwialog was written to use bash as its underlying shell no matter what the actual system shell is, hence all gtkdialog script should always work as intended.

**Comment by bm16ton** [comment]
Unbelievably awesome! As soon as I can compile it I will switch over! Not
being a programmer all I can contribute is a stupidly ez fix to have
aarch64 use the arm32 backwards patch. Ill make sure to keep checking your
github. I noticed 2 other people uploaded sum gtkdialog apps. I noticed
they both used gentoo not sure if they still have gtkdialog in that distro
or if its coincidence. Thank you again for your awesome work! Im looking
forward to using it!
